version: '3'
services:
  build_service:
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
    - .:/app_build
  test_build:
    build:
      context: .
      dockerfile: test_build/Dockerfile
    volumes:
    - .:/app_build
    ports:
    - 5000:5000
  db:
    image: postgres
    restart: always
    ports:
    - 65432:5432
    environment:
      POSTGRES_PASSWORD: example
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=pg_log -c log_statement=all
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis:6.0-rc1
    ports:
    - 63798:6379
